# --project-name cljstest

version: '3'


services:

  figwheel:
    build:
      context: .
      dockerfile: Dockerfile_figwheel
    volumes:
      - .:/home/theuser/theproject
      - ./lein-deps:/home/theuser/.m2/      # cache dependencies of lein figwheel to avoid downloading them on every run, this is gitignored
    working_dir: /home/theuser/theproject
    command: lein figwheel

  gulp:
    build:
      context: .
      dockerfile: Dockerfile_gulp
    volumes:
      - .:/home/node/theproject
    working_dir: /home/node/theproject
    command: gulp

